# Generated by Django 4.2.5 on 2023-10-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_remove_group_pet'),
        ('pets', '0002_rename_pets_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
            preserve_default=False,
        ),
    ]
