# Generated by Django 4.2.5 on 2023-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_pets_pet'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trair',
            name='pets',
            field=models.ManyToManyField(related_name='trair', to='pets.pet'),
        ),
    ]
