# Generated by Django 4.2.5 on 2023-10-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_pets_pet'),
        ('traits', '0002_trair_pets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trair',
            new_name='Trait',
        ),
    ]
